# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

services:
  db:
    container_name: db
    environment:
      - POSTGRES_DB=devices_api
      - POSTGRES_PASSWORD=devices_api
      - POSTGRES_USER=devices_api
      - PGTZ=America/Sao_Paulo
      - TZ=America/Sao_Paulo
    hostname: db
    image: postgres:17.3-bookworm
    ports:
      - 5432:5432
    restart: unless-stopped
    volumes:
      - .data:/var/lib/postgresql/data
