# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

services:
  db:
    container_name: db
    environment:
      - MYSQL_DATABASE=devices-api
      - MYSQL_PASSWORD=devices-api
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=devices-api
      - TZ=America/Sao_Paulo
    hostname: db
    image: mysql:8.4.4-oraclelinux9
    ports:
      - 3306:3306
    restart: unless-stopped
    volumes:
      - ./mysql:/var/lib/mysql
